# Generated by Django 5.2.11 on 2026-07-16 11:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='snaps/')),
                ('duration', models.IntegerField(blank=True, help_text='Тривалість від 1 до 10 секунд. Залиште порожнім для безлімітного перегляду.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('sent', 'Відправлено'), ('opened', 'Відкрито')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_snaps', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_snaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Снап',
                'verbose_name_plural': 'Снапи',
                'ordering': ['-created_at'],
            },
        ),
    ]
