# Generated by Django 5.2.11 on 2026-07-21 10:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_snap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to=users.models.user_avatar_path),
        ),
    ]
