# Generated by Django 5.2.11 on 2026-08-04 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='stories/', verbose_name='Медіафайл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час публікації')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Історія',
                'verbose_name_plural': 'Історії',
                'ordering': ['-created_at'],
            },
        ),
    ]
