# Generated by Django 5.2.11 on 2026-08-04 12:52

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='media_file',
            field=models.FileField(upload_to=users.models.story_file_path, verbose_name='Медіафайл'),
        ),
    ]
